export const userList = [
    {
        sname:"NSHIMIYE RUGWIRO",
        fname:"CLEMENT PASCAL",
        bd:"11/23/1998",
    },
    {
        sname:"NGABONZIZA",
        fname:"JACKSON",
        bd:"1/26/1996",
    },
    {
        sname:"NZABAKIRA",
        fname:"Floris",
        bd:"5/17/1999",
    },
    {
        sname:"NSHIMIYIMANA",
        fname:"Ismail",
        bd:"4/20/2000",
    },
    {
        sname:"ISHIMWE",
        fname:"Eredie",
        bd:"1/21/2000",
    },
    {
        sname:"IRADUKUNDA",
        fname:"Patrick",
        bd:"7/11/1999",
    },
    {
        sname:"URAKAZA",
        fname:"FEZA",
        bd:"1/1/2000",
    },
    {
        sname:"AKAYEZU",
        fname:"Marc",
        bd:"4/1/1998",
    },
    {
        sname:"UJENEZA",
        fname:"Evelyne",
        bd:"8/30/1999",
    },
    {
        sname:"NGIZENAYO",
        fname:"Penine",
        bd:"8/4/1998",
    },
    {
        sname:"NSHIMIYIMANA UWASE",
        fname:"Pascaline",
        bd:"8/4/1998",
    },
    {
        sname:"KWIZERA",
        fname:"Claude",
        bd:"1/1/1997",
    },
    {
        sname:"NIYIGABA",
        fname:"Derrick",
        bd:"1/1/1996",
    },
    {
        sname:"MUHAWENAYO",
        fname:"Jeannette",
        bd:"10/27/1997",
    },
    {
        sname:"UWITONZE",
        fname:"Claudette",
        bd:"7/20/1999",
    },
    {
        sname:"NTEZIRYAYO",
        fname:"Jean Tresor Yvan",
        bd:"3/15/2000",
    },
    {
        sname:"NDICUNGUYE",
        fname:"Steve",
        bd:"1/7/2000",
    },
    {
        sname:"SAFI",
        fname:"Emile",
        bd:"1/1/1998",
    },
    {
        sname:"IRADUKUNDA",
        fname:"Immaculee",
        bd:"10/14/1999",
    },
    {
        sname:"NGENDAHIMANA",
        fname:"Fidele",
        bd:"7/6/1997",
    },
    {
        sname:"INEMA",
        fname:"Ange Joyeuse",
        bd:"4/25/2000",
    },
    {
        sname:"KABUNDEGE KWIZERA",
        fname:"Christophe",
        bd:"8/3/1999",
    },
    {
        sname:"NIYONKURU",
        fname:"Pacifique",
        bd:"7/1/1998",
    },
    {
        sname:"NDATUMUREMYI",
        fname:"Paterne",
        bd:"4/15/1999",
    },
    {
        sname:"NIYINDAGIYE",
        fname:"Celestine",
        bd:"4/6/1998",
    },
    {
        sname:"HABIMANA IRAKIZA",
        fname:"Didier",
        bd:"12/20/1997",
    },
    {
        sname:"UWAMAHORO",
        fname:"Angelique",
        bd:"10/6/1999",
    },
    {
        sname:"NYIRINKWAYA",
        fname:"Arsene",
        bd:"11/6/1998",
    },
    {
        sname:"KIMENYI MUSEMINALI",
        fname:"Danny",
        bd:"4/29/1999",
    },
    {
        sname:"UMUHIRE",
        fname:"Anuarithe",
        bd:"1/1/1999",
    },
    {
        sname:"INGABIRE",
        fname:"Clemence",
        bd:"6/21/1999",
    },
    {
        sname:"ABIJURU KAMIKAZI",
        fname:"Marie Cynthia",
        bd:"1/9/2000",
    },
    {
        sname:"INGABIRE",
        fname:"Nadine",
        bd:"10/21/1999",
    },
    {
        sname:"RWIBUTSO",
        fname:"Serge",
        bd:"1/1/1998",
    },
    {
        sname:"BIZUMUREMYI",
        fname:"Honorathe",
        bd:"1/1/1996",
    },
    {
        sname:"UFITEYEZU",
        fname:"Chritella",
        bd:"9/15/2000",
    },
    {
        sname:"BERIMANA",
        fname:"Gloria",
        bd:"7/2/1999",
    },
    {
        sname:"NIYIGENA",
        fname:"Therese",
        bd:"7/14/1997",
    },
    {
        sname:"NIYONSENGA",
        fname:"Eric",
        bd:"1/1/1996",
    },
    {
        sname:"IRADUKUNDA",
        fname:"Mia Benitha",
        bd:"2/2/1998",
    },
    {
        sname:"UKUNDIWABO UWERA",
        fname:"Jeanne Aline",
        bd:"6/9/2000",
    },
    {
        sname:"UWIBAMBE",
        fname:"Angelique",
        bd:"2/20/1998",
    },
    {
        sname:"AYINKAMIYE",
        fname:"Adeline",
        bd:"8/1/1998",
    },
    {
        sname:"NKUNDIMANA",
        fname:"Eric",
        bd:"5/28/1996",
    },
    {
        sname:"ISINGIZWE",
        fname:"Clarisse",
        bd:"6/30/2000",
    },
    {
        sname:"NDINDIRIYIMANA",
        fname:"Eric",
        bd:"5/28/1998",
    },
    {
        sname:"IMENYABAYO",
        fname:"Xavier",
        bd:"10/10/1999",
    },
    {
        sname:"UMUTONI",
        fname:"Noella",
        bd:"12/25/1999",
    },
    {
        sname:"NKEZUWIMYE",
        fname:"David",
        bd:"6/25/1996",
    },
    {
        sname:"IRADUKUNDA",
        fname:"Alleluia Fiacre",
        bd:"5/10/1998",
    },
    {
        sname:"ISHIMWE GATETE",
        fname:"Olivier Hubert",
        bd:"5/29/2000",
    },
    
    {
        sname:"KWIZERA GASHIRABAKE",
        fname:"Elimine",
        bd:"2/25/1995",
    },
    {
        sname:"DUSHIME",
        fname:"Mechack",
        bd:"3/14/1998",
    },
    {
        sname:"IRAGUHA",
        fname:"Jean Baptiste",
        bd:"10/10/1997",
    },
    {
        sname:"KWIZERA",
        fname:"Aime Lambert",
        bd:"2/20/2000",
    },
    {
        sname:"BIZUMUNGU",
        fname:"Etienne",
        bd:"1/1/1997",
    },
    {
        sname:"TUYISHIME",
        fname:"Albert",
        bd:"1/1/2000",
    },
    {
        sname:"UWINGABIRE",
        fname:"Pascaline",
        bd:"7/4/1998",
    },
    {
        sname:"CYUZUZO",
        fname:"Yvette",
        bd:"2/26/2000",
    },
    {
        sname:"ISHIMWE",
        fname:"Allette",
        bd:"3/28/1997",
    },
    {
        sname:"UWIRINGIYIMANA",
        fname:"Jeannette",
        bd:"1/1/1998",
    },
    {
        sname:"SHIMWA UWASE",
        fname:"Sylvie",
        bd:"1/19/1999",
    },
    {
        sname:"NYIRARUKUNDO",
        fname:"Josianne",
        bd:"1/1/1997",
    },
    {
        sname:"UWIMANA",
        fname:"Darisa",
        bd:"1/1/1998",
    },
    {
        sname:"NYEMIGABO",
        fname:"Andy",
        bd:"1/27/1998",
    }
]
